### ISSUE TITLE
Clash between nexusformat and nexus packages (in the form of a warning)

### ISSUE THREAD

**Issue by willend** [conda-forge/nexus-feedstock#20]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In my [mcstas-suite](https://github.com/conda-forge/mcstas-suite-feedstock/tree/main) and [mcxtrace-suite](https://github.com/conda-forge/mcxtrace-suite-feedstock/tree/main) feedstocks I use dual NeXus oriented dependencies:

* The (admittedly oldschool) [nexus](https://github.com/conda-forge/nexus-feedstock/tree/main) c-API for writing NeXus files from McStas
* And [nexusformat](https://github.com/conda-forge/nexusformat-feedstock/) gets pulled in because I like providing my users with a nice and simple NeXus viewer (nexpy)

I have been noticing the below clash for file `bin/nxdir`which is part of both packages:

```
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: \ 
SafetyError: The package for nexus located at /Users/peterwillendrup/cleanconda/pkgs/nexus-4.4.3-h23a0a3c_13
appears to be corrupted. The path 'bin/nxdir'
has an incorrect size.
 reported size: 219856 bytes
 actual size: 279 bytes

ClobberError: This transaction has incompatible packages due to a shared path.
 packages: conda-forge/osx-arm64::nexus-4.4.3-h23a0a3c_13, conda-forge/noarch::nexusformat-1.0.6-pyhd8ed1ab_0
 path: 'bin/nxdir'



done
Executing transaction: done
```

Interestingly, the error (or let's call it a warning - because the resulting env is functional) only occurs when requesting nexus before nexusformat:
`conda create -n nexus1st nexus nexusformat`

but NOT when requesting 
`conda create -n nexusformat1st nexusformat nexus`

I have taken the liberty of creating a similar issue over at https://github.com/conda-forge/nexusformat-feedstock/issues/27 :-) 

### Installed packages

```shell
# packages in environment at /Users/peterwillendrup/cleanconda/envs/nexus1st:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.33.1               hd74edd7_0    conda-forge
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
h5py                      3.11.0          nompi_py312h903599c_102    conda-forge
hdf4                      4.2.15               h2ee6834_7    conda-forge
hdf5                      1.14.3          nompi_hec07895_105    conda-forge
hdf5plugin                5.0.0           py312hf6907c8_0    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libblas                   3.9.0           24_osxarm64_openblas    conda-forge
libcblas                  3.9.0           24_osxarm64_openblas    conda-forge
libcurl                   8.10.1               h13a7ad3_0    conda-forge
libcxx                    19.1.0               ha82da77_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.6.3                hf9b8971_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           24_osxarm64_openblas    conda-forge
libnghttp2                1.58.0               ha4dd798_1    conda-forge
libopenblas               0.3.27          openmp_h517c56d_1    conda-forge
libsqlite                 3.46.1               hc14010f_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libxml2                   2.12.7               h01dff8b_4    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
llvm-openmp               18.1.8               hde57baf_1    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
nexus                     4.4.3               h23a0a3c_13    conda-forge
nexusformat               1.0.6              pyhd8ed1ab_0    conda-forge
numpy                     2.1.1           py312h801f5e3_0    conda-forge
openssl                   3.3.2                h8359307_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
python                    3.12.6          h739c21a_1_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
scipy                     1.14.1          py312heb3a901_0    conda-forge
setuptools                74.1.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

### Environment info

```shell
active environment : nexus1st
    active env location : /Users/peterwillendrup/cleanconda/envs/nexus1st
            shell level : 2
       user config file : /Users/peterwillendrup/.condarc
 populated config files : /Users/peterwillendrup/cleanconda/.condarc
                          /Users/peterwillendrup/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m2
                          __conda=24.7.1=0
                          __osx=14.7=0
                          __unix=0=0
       base environment : /Users/peterwillendrup/cleanconda  (writable)
      conda av data dir : /Users/peterwillendrup/cleanconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/peterwillendrup/cleanconda/pkgs
                          /Users/peterwillendrup/.conda/pkgs
       envs directories : /Users/peterwillendrup/cleanconda/envs
                          /Users/peterwillendrup/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.5 Darwin/23.6.0 OSX/14.7 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.9
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

**Comment by beenje** [comment]
I must say I don't know what to do about that.

- `nexus` provides a C++ [nxdir](https://github.com/nexusformat/code/blob/master/applications/NXdir/CMakeLists.txt) executable
- `nexusformat` provides a pure python [nxdir](https://github.com/nexpy/nexusformat/blob/c96895ee0673fac67b3846b4bd47bd58f6a17c6b/setup.cfg#L49C1-L50C1) script

Both conda recipes only package the upstream code.
I don't really see one changing the `nxdir` name in the conda package. That would be very confusing for the users.

@conda-forge/core, is there any policy for this kind of issue?

**Comment by xhochy** [comment]
Normally, you would add a `run_constrainted` to at least one of the packages to make them non-coinstallable or split them apart that you can use a subset of the functionality without having the clashing parts. I'm not sure whether this is helpful here.

**Comment by willend** [comment]
@xhochy thanks for that feedback. No, not really helpful here as I in fact need them both. :-)

I will chat with some of the `nexus` folks at [NOBUGS](https://indico.esrf.fr/event/114/overview) this week, perhaps ideas can be found wrt. what to potentially do upstream on one or both.

Is there potentially a way to decide naming of the binary at install-time? (I.e. nxdir.packagename if there is an nxdir already?)

**Comment by xhochy** [comment]
> Is there potentially a way to decide naming of the binary at install-time? (I.e. nxdir.packagename if there is an nxdir already?)

There are no sane ways to do it. You could only do some trickery in post-link scripts, but I would highly advise against it.

**Comment by hmaarrfk** [comment]
you can split the packages into
```
nexus = libnexus +nexus-nxdir
nexusformat = libnexusformat + nexuformat-nxdir
```

then when you do have them co-installed, you can choose which `*-nxdir` you install.

eventually, you could make `nexus-nxdir` exclusive with `nexusformat-nxdir`

**Comment by beenje** [comment]
Thanks @hmaarrfk! That sounds like a good idea.

`nexusformat` being a python package, I don't think it's possible to split `nxdir` in a separate package. It's an entry-point that is created only at install time, not a file that can be put in a separate package. Or?

Anyway, splitting `nexus` and making `nexus-nxdir` exclusive with `nexusformat` could be enough.

What do you think @willend?
Will be interesting to know if `nexus` and `nexusformat` developers (ping @rayosborn) have some opinion.

**Comment by willend** [comment]
@beenje that _could_ work I guess, but I would then suggest to make `nexus` depend on `nexusformat || nexus-nxdir` 
(since I need both the `nexusformat` python and the libs+headers of `nexus` within the same env. :-) )

I will try to chat with @rayosborn in the next coffee break about his opinion.

**Comment by beenje** [comment]
> @beenje that _could_ work I guess, but I would then suggest to make `nexus` depend on `nexusformat || nexus-nxdir` (since I need both the `nexusformat` python and the libs+headers of `nexus` within the same env. :-) )

I'd split `nexus` in `nexus-core` and `nexus-nxdir`. By default it would install both to not break compatibility.
You could install `nexus-core` together with `nexusformat` (but would have to specify that explicitly instead of `nexus`).

**Comment by willend** [comment]
@beenje, perfect for me!

**Comment by hmaarrfk** [comment]
I forgot to say, if you think that both binaries are equivalent, then making one package depend on the other at build time would be the easiest. That way, only the first package will get the nxdir binary and the other will just get it transitively.

However, if the upstream packages are not co-aligned, then it is difficult to guarantee compatibility (even bug for bug compatibility)

**Comment by willend** [comment]
@hmaarrfk the two tools (one is a python script, the other is a binary built from c-code) are _equivalent_ and (I guess) probably drop-in compatible.

For a couple of reasons listed below I would be in favour of the last suggestion from @beenje (https://github.com/conda-forge/nexus-feedstock/issues/20#issuecomment-2376343799) - and my understanding is that @rayosborn is also OK with such an approach:

1. From my understanding of the usage in the community, the pure-python `nexusformat` package is probably more widely used these days, and there was actually quite official talk of deprecation of the (historic reference-implementation) c-api in the form of `nexus`.

2. (Official depreciation or not) We are still some that make use of the `nexus` c-api, so there are good reasons to set up a solution that is backward compatible for any other conda-forge feedstocks that depend on `nexus`.

3. My own softwares (on conda-forge as `mcstas-suite-feedstock` and `mcxtrace-suite-feedstock`) present a niche scenario that does not actually make use of the said binary `nxdir` - and I would therefore be happy to explicitly depend on a new `nexus-core` in the future.

So I guess a way forward is that I (or @beenje once you may have the time) have a go at the `nexus` feedstock in the direction of the proposal in https://github.com/conda-forge/nexus-feedstock/issues/20#issuecomment-2376343799 
(I will myself likely not have time for this until ~ mid October :-) )

**Comment by willend** [comment]
Excellent, thanks for your help @beenje
